// Country name / national team name → flag CDN code
// Used as fallback when team logos aren't available from the API
export const COUNTRY_FLAG_MAP: Record<string, string> = {
    'france': 'fr',
    'germany': 'de',
    'spain': 'es',
    'italy': 'it',
    'england': 'gb-eng',
    'portugal': 'pt',
    'netherlands': 'nl',
    'belgium': 'be',
    'brazil': 'br',
    'argentina': 'ar',
    'uruguay': 'uy',
    'colombia': 'co',
    'chile': 'cl',
    'peru': 'pe',
    'ecuador': 'ec',
    'venezuela': 've',
    'paraguay': 'py',
    'bolivia': 'bo',
    'mexico': 'mx',
    'usa': 'us',
    'canada': 'ca',
    'costa rica': 'cr',
    'panama': 'pa',
    'honduras': 'hn',
    'jamaica': 'jm',
    'japan': 'jp',
    'south korea': 'kr',
    'south korea republic': 'kr',
    'korea republic': 'kr',
    'korea': 'kr',
    'australia': 'au',
    'iran': 'ir',
    'iraq': 'iq',
    'saudi arabia': 'sa',
    'qatar': 'qa',
    'uae': 'ae',
    'united arab emirates': 'ae',
    'china': 'cn',
    'thailand': 'th',
    'vietnam': 'vn',
    'indonesia': 'id',
    'malaysia': 'my',
    'turkey': 'tr',
    'greece': 'gr',
    'switzerland': 'ch',
    'austria': 'at',
    'croatia': 'hr',
    'serbia': 'rs',
    'poland': 'pl',
    'czech republic': 'cz',
    'czechia': 'cz',
    'hungary': 'hu',
    'romania': 'ro',
    'bulgaria': 'bg',
    'slovakia': 'sk',
    'slovenia': 'si',
    'ukraine': 'ua',
    'russia': 'ru',
    'denmark': 'dk',
    'norway': 'no',
    'sweden': 'se',
    'finland': 'fi',
    'iceland': 'is',
    'scotland': 'gb-sct',
    'wales': 'gb-wls',
    'northern ireland': 'gb-nir',
    'ireland': 'ie',
    'israel': 'il',
    'morocco': 'ma',
    'egypt': 'eg',
    'tunisia': 'tn',
    'algeria': 'dz',
    'nigeria': 'ng',
    'ghana': 'gh',
    'senegal': 'sn',
    'cameroon': 'cm',
    'ivory coast': 'ci',
    "côte d'ivoire": 'ci',
    'south africa': 'za',
    'mali': 'ml',
    'burkina faso': 'bf',
    'gabon': 'ga',
    'guinea': 'gn',
    'zambia': 'zm',
    'zimbabwe': 'zw',
    'kenya': 'ke',
    'uganda': 'ug',
    'tanzania': 'tz',
    'new zealand': 'nz',
    'fiji': 'fj',
    'papua new guinea': 'pg',
    'india': 'in',
    'pakistan': 'pk',
    'bangladesh': 'bd',
    'sri lanka': 'lk',
    'nepal': 'np',
    'bhutan': 'bt',
    'maldives': 'mv',
    'afghanistan': 'af',
    'uzbekistan': 'uz',
    'kazakhstan': 'kz',
    'kyrgyzstan': 'kg',
    'tajikistan': 'tj',
    'turkmenistan': 'tm',
    'mongolia': 'mn',
    'north korea': 'kp',
    'laos': 'la',
    'cambodia': 'kh',
    'myanmar': 'mm',
    'philippines': 'ph',
    'singapore': 'sg',
    'brunei': 'bn',
    'timor-leste': 'tl',
    'tonga': 'to',
    'samoa': 'ws',
    'vanuatu': 'vu',
    'solomon islands': 'sb',
    'new caledonia': 'nc',
    'tahiti': 'pf',
    'cuba': 'cu',
    'haiti': 'ht',
    'dominican republic': 'do',
    'trinidad and tobago': 'tt',
    'guatemala': 'gt',
    'el salvador': 'sv',
    'nicaragua': 'ni',
    'belize': 'bz',
    'barbados': 'bb',
    'st. vincent and the grenadines': 'vc',
    'grenada': 'gd',
    'antigua and barbuda': 'ag',
    'st. kitts and nevis': 'kn',
    'dominica': 'dm',
    'st. lucia': 'lc',
    'guyana': 'gy',
    'suriname': 'sr',
    'french guiana': 'gf',
    'martinique': 'mq',
    'guadeloupe': 'gp',
    'curacao': 'cw',
    'curaçao': 'cw',
    'aruba': 'aw',
    'bermuda': 'bm',
    'cayman islands': 'ky',
    'turks and caicos islands': 'tc',
    'british virgin islands': 'vg',
    'us virgin islands': 'vi',
    'puerto rico': 'pr',
    'montserrat': 'ms',
    'anguilla': 'ai',
    'bosnia and herzegovina': 'ba',
    'north macedonia': 'mk',
    'montenegro': 'me',
    'albania': 'al',
    'kosovo': 'xk',
    'moldova': 'md',
    'belarus': 'by',
    'lithuania': 'lt',
    'latvia': 'lv',
    'estonia': 'ee',
    'georgia': 'ge',
    'armenia': 'am',
    'azerbaijan': 'az',
    'liechtenstein': 'li',
    'luxembourg': 'lu',
    'malta': 'mt',
    'cyprus': 'cy',
    'andorra': 'ad',
    'san marino': 'sm',
    'monaco': 'mc',
    'faroe islands': 'fo',
    'gibraltar': 'gi',
    'greenland': 'gl',
    'sudan': 'sd',
    'libya': 'ly',
    'ethiopia': 'et',
    'eritrea': 'er',
    'somalia': 'so',
    'djibouti': 'dj',
    'comoros': 'km',
    'madagascar': 'mg',
    'mauritius': 'mu',
    'seychelles': 'sc',
    'reunion': 're',
    'mayotte': 'yt',
    'cape verde': 'cv',
    'guinea-bissau': 'gw',
    'gambia': 'gm',
    'sierra leone': 'sl',
    'liberia': 'lr',
    'togo': 'tg',
    'benin': 'bj',
    'niger': 'ne',
    'chad': 'td',
    'central african republic': 'cf',
    'equatorial guinea': 'gq',
    'sao tome and principe': 'st',
    'congo': 'cg',
    'dr congo': 'cd',
    'democratic republic of the congo': 'cd',
    'rwanda': 'rw',
    'burundi': 'bi',
    'angola': 'ao',
    'namibia': 'na',
    'botswana': 'bw',
    'lesotho': 'ls',
    'eswatini': 'sz',
    'swaziland': 'sz',
    'mozambique': 'mz',
    'malawi': 'mw',
    'mauritania': 'mr',
    'western sahara': 'eh',
    'somaliland': 'xs',
    'palestine': 'ps',
    'jordan': 'jo',
    'lebanon': 'lb',
    'syria': 'sy',
    'yemen': 'ye',
    'oman': 'om',
    'kuwait': 'kw',
    'bahrain': 'bh',
};

export function getCountryFlagUrl(teamName: string): string | undefined {
    if (!teamName) return undefined;
    const code = COUNTRY_FLAG_MAP[teamName.toLowerCase().trim()];
    if (!code) return undefined;
    return `https://flagcdn.com/w80/${code}.png`;
}
